# Use lightweight Java 17 image
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

# Copy JAR
COPY target/user-service-0.0.1-SNAPSHOT.jar app.jar

# Expose port
EXPOSE 8081

# Run application
ENTRYPOINT ["java", "-jar", "app.jar"]
